# Generated by Django 6.0.1 on 2026-02-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq_test', '0002_question_image_question_option_a_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='correct_count',
            field=models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar"),
        ),
        migrations.AddField(
            model_name='userresult',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami savollar'),
        ),
    ]
