# Generated by Django 6.0.1 on 2026-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq_test', '0003_userresult_correct_count_userresult_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi'),
        ),
    ]
